{% set name = "iowait" %}
{% set version = "0.2" %}
{% set sha256 = "ab1bc2eb84c22ccf61f17a0024f9fb6df781b39f1852764a66a7769d5adfb299" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - iowait

about:
  home: https://launchpad.net/python-iowait
  license: LGPL 3.0
  license_file: COPYING
  license_family: LGPL
  summary: Platform-independent module for I/O completion events

extra:
  recipe-maintainers:
    - vamega
