travis:
  secure:
    BINSTAR_TOKEN: a8I4ZpwhVSfSfyCx7PrTCmDju7HlfWoYON0ju4GufnBWmQF+LgXBenDJwLdJ62J1Tfd6Ejxa/17vzyDVfWOUdiW0SxqzEtLquDNX0a/JWNnjydVp8ivEdVL5bOneoSYkEijT++jnS5TbomNxpo+UHhLvUB6xck/ThIlAj5wbI3OwvIM3G6nkcMYRSFhW+vRRskH1Cbkq68ddaA2NLQlJBerO28MlDoyb7ByX7zB+QpjhHIYZok73fXDw/gwXOLH30JhXpRZyziXUdkBN00GNQaRH4hUQbMVsecSXnHvE3q+Ah765tSB3qolII7kxL3tcZVEo6USdeQmq7dmHSITRMPGGoIO9zakruFB6/pXmfgVZy1U9Gy/hm6wJV4unoQ0Jm3mFiRcnByTShVCdJKcP/G2vqn+/6hluI0/K/XbkGaO6D1RN3jhVfwhiiiHHjy1qa+/Suxs9ick0DsqtQ7ebRxlmqd8ammHs30ALDxoGSjFpUlafbAj4MnTuRr2BX3s4d3q6S4ZUveGDTCcYpmxzNabjkeIUisRxWF25JvF9+2q7ubqn16AZKupDiOcfqMC6jo5slOOCjuIRbELB3I7jbHuMkkslJE7h5KJ+bfaKBdCYvlgdO+mOfLbbB10GRwRvwLeXCowL9ILMKGi9ljzCeVDeGLUMXh84MWA3NFEh2dw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
