travis:
  secure:
    BINSTAR_TOKEN: DZWrgPpKdQF6BvkIOVanK5JTnWc9g1JgVWyxmSxgqIuAamMjKUdjrAiPQEQfk6z8VeySQf12udB/8JPp6Zw9U8YWjhptcmtzzwm2lEx8kHYJPEZGTMGDS/wjToi1AXtL7HD2hg+TLyI3P1KF3TcUBLpHCFr3OCYuZsCZuy7LRe81dDOiTnNbGvG0bGRn8cH2bI6QmLSh0KR9i2Qcj3+RJxJwkdCrjXSvxR1fCoDMKBiKJT/ulW6Bek63t4NnBDNW2+kc3piVcCTF5YLYfLZtTp6GvAXmqj/W9hVaGJ1LnvHvUP7G8UlaOWESPCraYxLuR4LGCw1x+1NoBGDuQY2NAnsLIZ3P9EI6r1YMLRRGItuayQQW7DsNFl0z+vpLxFpEylFqopFjp/2GuRtoIdn5yEWmNrfVVve8OscruIXWMv3WE9/jlm3P5CWZkLEw66H8HJK15+ImtD3mhOlpSZFjji2uzXw0lXuK2rr5gSl3itgMZfN+SxGqkqZOXPXWE7mmC+yuVzE42jtp26TzDN3N3GHSAYYxbXV5JWNhP+apqVdRwi1QIsJWWTpxPKGGrlk2kBl0iljK8on7rfsaX09Hr/CRMvG9Vnszk4DoEGkWw/J8sV4iykjrTvzdaxOEbGP/0UwmnkvDrerXUBQS7BdgbDfLP0pXB2CguYpipreaT6g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
